const fs = require('fs');
const lines = [];

function add(s) { lines.push(s); }

add('import { getLogger } from "../../config/logger";');
add('import { execSync } from "child_process";');
add('');
add('const logger = getLogger();');
add('');
add('export interface AuditIssue {');
add('  severity: "red_flag" | "warning" | "info"');
add('  category: string');
add('  message: string');
add('  line?: number');
add('  file?: string');
add('}');
add('');
add('export interface AuditResult {');
add('  proposedCommit: string');
add('  baseCommit: string');
add('  totalScore: number');
add('  passed: boolean');
add('  redFlags: number');
add('  warnings: number');
add('  issues: AuditIssue[]');
add('  summary: string');
add('  rawReport: string');
add('  reviewedAt: number');
add('}');
add('');
add('export class AICodeAuditor {');
add('  private apiKey: string;');
add('  constructor() { this.apiKey = process.env.OPENAI_API_KEY || ""; }');
add('  async initialize(): Promise<boolean> {');
add('    logger.info("AICodeAuditor: " + (this.apiKey ? "AI+static" : "static"));');
add('    return true;');
add('  }');
add('  async auditUpgrade(pc: string, bc: string): Promise<AuditResult> {');
add('    const diff = this.getDiff(pc, bc);');
add('    if (!diff) return this.fail(pc, bc, "no diff");');
add('    const issues = this.scan(diff);');
add('    if (this.apiKey) {');
add('      const ai = await this.aiScan(diff);');
add('      if (ai) ai.forEach(i => issues.push(i));');
add('    }');
add('    return this.score(pc, bc, issues);');
add('  }');
add('  private getDiff(a: string, b: string): string | null {');
add('    try { return execSync("git diff " + a + ".." + b).toString(); }');
add('    catch { return null; }');
add('  }');
add('  private scan(d: string): AuditIssue[] {');
add('    const r: AuditIssue[] = [];');
add('    const ls = d.split(String.fromCharCode(10));');
add('    for (let i = 0; i < ls.length; i++) {');
add('      const l = ls[i];');
add('      if (!l.startsWith("+")) continue;');
add('      if (/0x[a-fA-F0-9]{40}/.test(l)) r.push({severity:"red_flag",category:"资金安全",message:"硬编码地址",line:i+1});');
add('      if (/(passphrase|secret|privateKey)\s*=\s*/.test(l)) r.push({severity:"red_flag",category:"资金安全",message:"硬编码密钥",line:i+1});');
add('      if (/isAdmin|adms*=\s*true/i.test(l)) r.push({severity:"red_flag",category:"权限治理",message:"硬编码管理员",line:i+1});');
add('      if (/eval\s*\(|Function\s*\(/.test(l)) r.push({severity:"red_flag",category:"代码质量",message:"动态代码执行",line:i+1});');
add('      if (l.indexOf("http") >= 0) {');
add('        const ok = ["trongrid.io","github.com","stripe.com","porkbun.com","namesilo.com","cloudflare.com"];');
add('        if (!ok.some(h => l.indexOf(h) >= 0)) r.push({severity:"red_flag",category:"数据安全",message:"未知网络请求",line:i+1});');
add('      }');
add('    }');
add('    return r;');
add('  }');
add('  private async aiScan(d: string): Promise<AuditIssue[] | null> {');
add('    try {');
add('      const axios = require("axios");');
add('      const p = "Audit code diff. JSON reply:{score,passed,issues:[{severity,category,message}],summary}. DIFF:" + d.substring(0,15000);');
add('      const resp = await axios.post("https://api.openai.com/v1/chat/completions",');
add('        {model:"gpt-4",messages:[{role:"user",content:p}],temperature:0.1,max_tokens:2000},');
add('        {headers:{Authorization:"Bearer "+this.apiKey},timeout:60000});');
add('      const t = resp.data?.choices?.[0]?.message?.content || "";');
add('      try { const j = JSON.parse(t); if (j.issues) return j.issues.map((i:any) => ({severity:i.severity||"info",category:i.category||"AI",message:i.message})); } catch {}');
add('    } catch {}');
add('    return null;');
add('  }');
add('  private score(pc: string, bc: string, issues: AuditIssue[]): AuditResult {');
add('    const rf = issues.filter(i => i.severity === "red_flag").length;');
add('    const wn = issues.filter(i => i.severity === "warning").length;');
add('    if (rf > 0) return this.fail(pc, bc, "REJECTED: " + rf + " red flags");');
add('    const score = Math.max(0, 100 - wn * 10);');
add('    const passed = score >= 70;');
add('    const sm = score >= 90 ? "PASS" : score >= 70 ? "PASS(warn)" : "FAIL(" + score + ")";');
add('    return {proposedCommit:pc,baseCommit:bc,totalScore:score,passed,redFlags:rf,warnings:wn,issues,summary:sm,rawReport:"",reviewedAt:Date.now()};');
add('  }');
add('  private fail(pc: string, bc: string, r: string): AuditResult {');
add('    return {proposedCommit:pc,baseCommit:bc,totalScore:0,passed:false,redFlags:1,warnings:0,issues:[],summary:r,rawReport:"",reviewedAt:Date.now()};');
add('  }');
add('  isReady(): boolean { return true; }');
add('}');
add('');

fs.writeFileSync('src/modules/audit/AICodeAuditor.ts', lines.join('
'), 'utf8');
console.log('Written: ' + lines.length + ' lines');
